/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lamelltelas;

import javax.swing.JOptionPane;
import lamell.Conexao;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author vinic
 */
public class CadastroPedidos extends javax.swing.JFrame {
    

    /**
     * Creates new form CadastroPedidos
     */
    public CadastroPedidos() {
        initComponents();
         carregarClientes();     // chama os métodos ao iniciar a tela
        carregarProdutos();

        CbxSituacao.removeAllItems();
        CbxSituacao.addItem("Em aberto");
        CbxSituacao.addItem("Finalizado");
        CbxSituacao.addItem("Cancelado");

        CbxQuantidade.removeAllItems();
        for (int i = 1; i <= 10; i++) {
            CbxQuantidade.addItem(String.valueOf(i));
        }
    }

    private void carregarClientes() {
        Conexao conexao = new Conexao();
        if (conexao.conectar()) {
            try {
                String sql = "SELECT id, nome FROM clientes";
                PreparedStatement ps = conexao.getConnection().prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                CbxCliente.removeAllItems();

                while (rs.next()) {
                    int id = rs.getInt("id");
                    String nome = rs.getString("nome");
                    CbxCliente.addItem(id + " - " + nome);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar clientes: " + e.getMessage());
            }
        }
    }

    private void carregarProdutos() {
        Conexao conexao = new Conexao();
        if (conexao.conectar()) {
            try {
                String sql = "SELECT id, nome FROM produtos";
                PreparedStatement ps = conexao.getConnection().prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                CbxProduto.removeAllItems();

                while (rs.next()) {
                    int id = rs.getInt("id");
                    String nome = rs.getString("nome");
                    CbxProduto.addItem(id + " - " + nome);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CbxCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CbxProduto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CbxSituacao = new javax.swing.JComboBox<>();
        BtnCadastrar = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CbxQuantidade = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro pedidos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Selecione o cliente");

        CbxCliente.setBackground(new java.awt.Color(255, 204, 255));
        CbxCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbxCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Selecione o produto");

        CbxProduto.setBackground(new java.awt.Color(255, 204, 255));
        CbxProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbxProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Selecione a situacao");

        CbxSituacao.setBackground(new java.awt.Color(255, 204, 255));
        CbxSituacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbxSituacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnCadastrar.setBackground(new java.awt.Color(255, 204, 255));
        BtnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        BtnMenu.setBackground(new java.awt.Color(255, 204, 255));
        BtnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnMenu.setText("Voltar");
        BtnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Quantidade");

        CbxQuantidade.setBackground(new java.awt.Color(255, 204, 255));
        CbxQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CbxQuantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCadastrar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(CbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(CbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(CbxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar)
                    .addComponent(BtnMenu))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed

        this.dispose();
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        String cliente = CbxCliente.getSelectedItem().toString();
        String produto = CbxProduto.getSelectedItem().toString();
        String situacao = CbxSituacao.getSelectedItem().toString();
        int quantidade = Integer.parseInt(CbxQuantidade.getSelectedItem().toString());
        int idCliente = Integer.parseInt(cliente.split(" - ")[0]);
        int idProduto = Integer.parseInt(produto.split(" - ")[0]);
        
        Conexao conexao = new Conexao();
      if (conexao.conectar()) {
    try {
       
        String sqlEstoque = "SELECT estoque FROM produtos WHERE id = ?";
        PreparedStatement psEstoque = conexao.getConnection().prepareStatement(sqlEstoque);
        psEstoque.setInt(1, idProduto);
        ResultSet rs = psEstoque.executeQuery();

        if (rs.next()) {
            int estoque = Integer.parseInt(rs.getString("estoque"));

            if (quantidade > estoque) {
                JOptionPane.showMessageDialog(this, "Estoque insuficiente!");
                return;
            }

          
            String sql = "INSERT INTO pedidos (situacao, fk_cliente_id, FK_produto_id) VALUES (?, ?, ?)";
            PreparedStatement ps = conexao.getConnection().prepareStatement(sql);
            ps.setString(1, situacao);
            ps.setInt(2, idCliente);
            ps.setInt(3, idProduto);
            ps.executeUpdate();

          
            int novoEstoque = estoque - quantidade;
            String sqlUpdate = "UPDATE produtos SET estoque = ? WHERE id = ?";
            PreparedStatement psUpdate = conexao.getConnection().prepareStatement(sqlUpdate);
            psUpdate.setString(1, String.valueOf(novoEstoque)); // estoque ainda é VARCHAR
            psUpdate.setInt(2, idProduto);
            psUpdate.executeUpdate();

            JOptionPane.showMessageDialog(this, "Pedido cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
}
       this.dispose();
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JComboBox<String> CbxCliente;
    private javax.swing.JComboBox<String> CbxProduto;
    private javax.swing.JComboBox<String> CbxQuantidade;
    private javax.swing.JComboBox<String> CbxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
